### ISSUE TITLE
Cannot upload a photo if the size is more than 

### ISSUE THREAD

**Issue by benpro** [pixelfed/support#11]
![Screenshot_20190727_161639](https://user-images.githubusercontent.com/1057913/61995517-f17cb200-b089-11e9-9f7d-92ea8a2ef088.png)

If I upload a photo with a size superior to 1900kB it produce error.

Steps to reproduce:
* Get a big picture
* Compress to 1900kB `jpegoptim -S1900`
* Upload
* It works

* Get a big picture
* Keep it superior to 1900kB, i.e. 2000kB `jpegoptim -S2000`
* Upload
* It fails.

Logs:

```
[2019-07-27 14:15:59] production.ERROR: The "" file does not exist or is not readable. {"userId":1,"exception":"[object] (Symfony\\Component\\Mime\\Exception\\InvalidArgumentException(code: 0): The \"\" file does not exist or is not readable. at /home/pixelfed/vendor/symfony/mime/FileinfoMimeTypeGuesser.php:52)
[stacktrace]
#0 /home/pixelfed/vendor/symfony/mime/MimeTypes.php(136): Symfony\\Component\\Mime\\FileinfoMimeTypeGuesser->guessMimeType('')
pixelfed/pixelfed#1 /home/pixelfed/vendor/symfony/http-foundation/File/File.php(73): Symfony\\Component\\Mime\\MimeTypes->guessMimeType('')
pixelfed/pixelfed#2 /home/pixelfed/app/Http/Controllers/Api/BaseApiController.php(249): Symfony\\Component\\HttpFoundation\\File\\File->getMimeType()
pixelfed/pixelfed#3 [internal function]: App\\Http\\Controllers\\Api\\BaseApiController->uploadMedia(Object(Illuminate\\Http\\Request))
pixelfed/pixelfed#4 /home/pixelfed/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
[…]
```

```
[27/Jul/2019:14:15:59 +0000] "POST /api/v1/media HTTP/1.1" 500 44 "https://pix.benpro.fr/" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
```

.env:

```
MAX_PHOTO_SIZE=15000 (is it in kB?)
```

**Comment by mikail97** [comment]
The same thing is happening to me, where I find the file in which I can modify the size?
Thanks in advance! @benpro

**Comment by janboddez** [comment]
If you enable debugging, do you see values for the different settings at the very bottom of the Share on Pixelfed settings page? Is the instance still correctly connected? Example:
![afbeelding](https://user-images.githubusercontent.com/8428432/168235923-129464d5-7fe8-4c68-a859-ebb9b9f1841b.png)

If you don't see any error/server response in the log, that would indicate an error here, an unsupported post type, or that the post was already shared.

Can you also add the following to your newly create mu-plugin file?
```
add_filter( 'is_protected_meta', '__return_false' ); 
```
After that, can you go to the Edit screen, in the admin interface, for that post, and enable the Custom Fields view/meta box?

Should look something like this:
![afbeelding](https://user-images.githubusercontent.com/8428432/168236677-9ed979ab-682d-4694-ba53-2af7451df7e8.png)

Just want to make sure there really isn't a value for `_share_on_pixelfed_url`.

It could also be a server error, maybe they're configured to not accept photos over a certain size? Although in that case I would expect a response clarifying what's wrong.

**Comment by trwnh** [comment]
> The same thing is happening to me, where I find the file in which I can modify the size?

@mikail97 you want to edit `php.ini` which can usually be found in `/etc/php` or similar
