### ISSUE TITLE
Locating the correct php.ini file for upload size limits

### ISSUE THREAD

**Issue by dallasgroot** [pixelfed/support#117]
Hey guys I successfully have Pixelfed running on an RP3b+ but i'm running into issues with uploading images from my phone because they are too large in size.

I'm somwhat a noob when it comes to server stuff, but i'm always learning as I go. I'm trying to figure out the locations 
```
post_max_size 
file_uploads
upload_max_filesize
max_file_uploads
max_execution_time
```

I can't find these in my .env file but i did change it in my php.ini file but after changing and running `php artisan config:cache` the changes don't take effect. Any help would be appreciated. don't mean to spam the issues section.

**Comment by trwnh** [comment]
This depends on your distro, but I think you can run `php-fpm -i`

also you might have to restart php-fpm

**Comment by dallasgroot** [comment]
Thanks for pointing me in the right direction.  Unfortunately I get
`pi@raspberrypi:~ $ php-fpm -i-
bash: php-fpm: command not found `

**Comment by dallasgroot** [comment]
My php version is 7.4.13

**Comment by trwnh** [comment]
You're looking for the config file specifically, right? In any case though, you should have PHP-FPM installed, I'm pretty sure...

**Comment by dallasgroot** [comment]
I do have php-fpm installed, but running php-fpm -v does nothing, at least for me. I saw it in the instructions too. i did `php -ini` and found out its in /etc/php/7.4/cli. Just edited it in there so i hope that works. In the 7.4 folder i also have a fpm folder

**Comment by joshkitterman** [comment]
That's likely the one you want: /etc/php/7.4/fpm/php.ini

**Comment by joshkitt** [comment]
That's likely the one you want: /etc/php/7.4/fpm/php.ini
