### ISSUE TITLE
‘Can't write image data to path’ when posting any photo 

### ISSUE THREAD

**Issue by dallasgroot** [pixelfed/support#118]
System RP3b+
Raspbian 32-bit Buster

Hey, trying to trouble shoot as to why I cannot write to the public directory. The directories do exist. 

`[2021-01-24 22:07:54] production.ERROR: Can't write image data to path (/home/pi/www/pixelfed/storage/app/public/m/_v2/1/8fb78bfd7-ec88b5/iPUpaMJOhEke/vdGX3IAjgBoitwqhAGtqzo04hYnOUAuH2nYnPzVt.jpg) {"exception":"[object] (Intervention\\Image\\Exception\\NotWritableException(code: 0): Can't write image data to path (/home/pi/www/pixelfed/storage/app/public/m/_v2/1/8fb78bfd7-ec88b5/iPUpaMJOhEke/vdGX3IAjgBoitwqhAGtqzo04hYnOUAuH2nYnPzVt.jpg) at /home/pi/www/pixelfed/vendor/intervention/image/src/Intervention/Image/Image.php:150)
[stacktrace]
#0 /home/pi/www/pixelfed/app/Util/Media/Image.php(167): Intervention\\Image\\Image->save()
#1 /home/pi/www/pixelfed/app/Util/Media/Image.php(93): App\\Util\\Media\\Image->handleImageTransform()
#2 /home/pi/www/pixelfed/app/Util/Media/Image.php(81): App\\Util\\Media\\Image->handleResizeImage()
#3 /home/pi/www/pixelfed/app/Jobs/ImageOptimizePipeline/ImageResize.php(54): App\\Util\\Media\\Image->resizeImage()
#4 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\ImageOptimizePipeline\\ImageResize->handle()
#5 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#7 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#8 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#9 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#10 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#11 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#13 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(118): Illuminate\\Bus\\Dispatcher->dispatchNow()
#14 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#15 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Pipeline\\Pipeline->then()
#17 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#18 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#19 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(406): Illuminate\\Queue\\Jobs\\Job->fire()
#20 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Worker->process()
#21 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\\Queue\\Worker->runJob()
#22 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(116): Illuminate\\Queue\\Worker->daemon()
#23 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#24 /home/pi/www/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(50): Illuminate\\Queue\\Console\\WorkCommand->handle()
#25 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#26 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#27 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#28 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#29 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#30 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#31 /home/pi/www/pixelfed/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#32 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#33 /home/pi/www/pixelfed/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#34 /home/pi/www/pixelfed/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#35 /home/pi/www/pixelfed/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#36 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#37 /home/pi/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#38 /home/pi/www/pixelfed/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#39 {main}
"}  `

**Comment by dallasgroot** [comment]
` /home/pi/www/pixelfed/storage/app/public/m/_v2/1/8fb78bfd7-ec88b5/iPUpaMJOhEke/vdGX3IAjgBoitwqhAGtqzo04hYnOUAuH2nYnPzVt.jpg` does exist  as well

I've ran 
```
cd pixelfed
sudo chown -R www-data:www-data . # change user/group to http user and http group
sudo find . -type d -exec chmod 755 {} \; # set all directories to rwx by user/group
sudo find . -type f -exec chmod 644 {} \; # set all files to rw by user/group
```
but i'm still stuck with the same error in my larvel.log.

**Comment by dallasgroot** [comment]
upon rebooting my pi, and re trying i am now encountering a different error (progress??)

`[2021-01-25 00:26:18] production.ERROR: Error while reading line from the server. [tcp://127.0.0.1:6379] {"exception":"[object] (Predis\\Connection\\ConnectionException(code: 0): Error while reading line from the server. [tcp://127.0.0.1:6379] at /home/pi/www/pixelfed/vendor/predis/predis/src/Connection/AbstractConnection.php:155)
[stacktrace]` which seems to be an issue with redis... hmmm

**Comment by dallasgroot** [comment]
When running Horizon, i can see it erroring out, this is the error:
`php artisan horizon
Horizon started successfully.
[2021-01-25 00:38:57][7dd8c2d2-4f3c-43bf-9136-64acb11f9d97] Processing: App\Jobs\ImageOptimizePipeline\ImageOptimize
[2021-01-25 00:38:57][7dd8c2d2-4f3c-43bf-9136-64acb11f9d97] Processed:  App\Jobs\ImageOptimizePipeline\ImageOptimize
[2021-01-25 00:38:57][52d6c4ff-de34-4b83-b3f0-c5745641e5ae] Processing: App\Jobs\ImageOptimizePipeline\ImageResize

   UnexpectedValueException 

  The stream or file "/home/pi/www/pixelfed/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

  at vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:111
    107▕             restore_error_handler();
    108▕             if (!is_resource($this->stream)) {
    109▕                 $this->stream = null;
    110▕ 
  ➜ 111▕                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $this->url));
    112▕             }
    113▕         }
    114▕ 
    115▕         if ($this->useLocking) {

      +7 vendor frames 
  8   app/Exceptions/Handler.php:38
      Illuminate\Foundation\Exceptions\Handler::report()

      +2 vendor frames 
  11  [internal]:0
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleException()`

**Comment by dallasgroot** [comment]
When running php artisan self-diagnosis command, It appears that i get an endless loops of dependancies error, but i'm not sure which dependency i'm missing as when i run composer install nothing is fixed 

`pi@raspberrypi:~/www/pixelfed $ php artisan self-diagnosis
|-------------------------------------
| Common Checks
|-------------------------------------
Running check 1/10: App key is set...  ✔
Running check 2/10: The correct PHP version is installed...  ✔
Running check 3/10: The database can be accessed...  ✔
Running check 4/10: All directories have the correct permissions...  ✔
Running check 5/10: The environment file exists...  ✔
Running check 6/10: Maintenance mode is not enabled...  ✔
Running check 7/10: The migrations are up to date...  ✔
Running check 8/10: The required PHP extensions are installed...  ✔
Running check 9/10: The Redis cache can be accessed...  ✔
Running check 10/10: The storage directory is linked...  ✔

|-------------------------------------
| Environment Specific Checks (production)
|-------------------------------------
Running check 1/5: Composer dependencies (without dev) are up to date...  ✘
Running check 2/5: Configuration is cached...  ✔
Running check 3/5: Debug mode is not enabled...  ✔
Running check 4/5: Unwanted PHP extensions are disabled...  ✔
Running check 5/5: Routes are cached...  ✔

The following checks failed:
Your composer dependencies are not up to date. Call "composer install" to update them. Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 0 installs, 0 updates, 39 removals
  - Removing theseer/tokenizer (1.2.0)
  - Removing sebastian/version (3.0.2)
  - Removing sebastian/type (2.3.1)
  - Removing sebastian/resource-operations (3.0.3)
  - Removing sebastian/recursion-context (4.0.4)
  - Removing sebastian/object-reflector (2.0.4)
  - Removing sebastian/object-enumerator (4.0.4)
  - Removing sebastian/lines-of-code (1.0.3)
  - Removing sebastian/global-state (5.0.2)
  - Removing sebastian/exporter (4.0.3)
  - Removing sebastian/environment (5.1.3)
  - Removing sebastian/diff (4.0.4)
  - Removing sebastian/complexity (2.0.2)
  - Removing sebastian/comparator (4.0.6)
  - Removing sebastian/code-unit-reverse-lookup (2.0.3)
  - Removing sebastian/code-unit (1.0.8)
  - Removing sebastian/cli-parser (1.0.1)
  - Removing phpunit/phpunit (9.5.1)
  - Removing phpunit/php-timer (5.0.3)
  - Removing phpunit/php-text-template (2.0.4)
  - Removing phpunit/php-invoker (3.1.1)
  - Removing phpunit/php-file-iterator (3.0.5)
  - Removing phpunit/php-code-coverage (9.2.5)
  - Removing phpspec/prophecy (1.12.2)
  - Removing phpdocumentor/type-resolver (1.4.0)
  - Removing phpdocumentor/reflection-docblock (5.2.2)
  - Removing phpdocumentor/reflection-common (2.2.0)
  - Removing phar-io/version (3.0.4)
  - Removing phar-io/manifest (2.0.1)
  - Removing nunomaduro/collision (v5.2.0)
  - Removing myclabs/deep-copy (1.10.2)
  - Removing mockery/mockery (1.4.2)
  - Removing hamcrest/hamcrest-php (v2.0.1)
  - Removing fzaninotto/faker (v1.9.2)
  - Removing filp/whoops (2.9.2)
  - Removing facade/ignition-contracts (1.0.2)
  - Removing facade/ignition (2.5.8)
  - Removing facade/flare-client-php (1.3.7)
  - Removing doctrine/instantiator (1.4.0)
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
89 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
pi@raspberrypi:~/www/pixelfed $ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: beyondcode/laravel-self-diagnosis
Discovered Package: buzz/laravel-h-captcha
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: intervention/image
Discovered Package: jenssegers/agent
Discovered Package: laravel/horizon
Discovered Package: laravel/passport
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: pbmedia/laravel-ffmpeg
Discovered Package: pixelfed/laravel-snowflake
Discovered Package: spatie/laravel-backup
Discovered Package: spatie/laravel-image-optimizer
Discovered Package: stevebauman/purify
Package manifest generated successfully.
89 packages you are using are looking for funding.
Use the `composer fund` command to find out more!`

**Comment by trwnh** [comment]
run `ls -la /home/pi/www/pixelfed/storage/app/public/m/_v2/1/8fb78bfd7-ec88b5/iPUpaMJOhEke/` for me?

**Comment by dallasgroot** [comment]
Thanks for the reply. 
```
$ ls -la /home/pi/www/pixelfed/storage/app/public/m/_v2/1/8fb78bfd7-ec88b5/iPUpaMJOhEke/
total 56
drwxrwxrwx  2 www-data www-data  4096 Jan 24 14:07 .
drwxrwxrwx 43 www-data www-data  4096 Jan 26 16:00 ..
-rwxrwxrwx  1 www-data www-data 48458 Jan 24 14:07 vdGX3IAjgBoitwqhAGtqzo04hYnOUAuH2nYnPzVt.jpg 
```
Is the output.

**Comment by dallasgroot** [comment]
I'm closing this with no solution. Somewhere along the way i messed up and wasn't able to pin point it, so i restarted from scratch, double checked  everything and to my surprise, its working with image posting working woot! Now I just need to play around with settings.
