### ISSUE TITLE
Unable to change MAX_CAPTION_LENGTH

### ISSUE THREAD

**Issue by nuciluc** [pixelfed/support#129]
Dear team,
I installed Pixelfed using v0.10.10 tar.gz.
I followed "Generic installation guide" so I copied .env.example and modified it, where MAX_CAPTION_LENGTH is 150. 

Later I wanted to set an higher value, but it is not working:
- /api/v1/instance has correct value
- /site/kb/sharing-media has correct value
 
But when I add a post, I can not write more than 150 characters.

**Comment by trwnh** [comment]
if you ran `php artisan config:cache` then you need to run it again

EDIT: you apparently also need to run `php artisan cache:clear` because it's cached at the api level according to dansup

**Comment by nuciluc** [comment]
I tried multiple times, without result.
I solved rebooting the server.

**Comment by Yetangitu** [comment]
Old post but still:

```
php artisan config:clear
php artisan config:cache
```

...and it works
