### ISSUE TITLE
Fresh install: Edit post button does not appear to be working

### ISSUE THREAD

**Issue by samihsoylu** [pixelfed/support#137]
Steps to reproduce

1. Upload a single/multiple new photo (create a post), and write a description.
2. Attempt to edit the description and receive a "Sorry, this page isn't available."

Link in browser I am attempting to load: `https://pixelfed.it/p/samihsoylu/367748572262912001/edit`

## Instance information
```
=======================
 Instance Diagnostic 
=======================
APP_URL: https://pixelfed.it
APP_DOMAIN: pixelfed.it
Version: 0.11.1
PHP: 7.3.33-1+0~20211119.91+debian11~1.gbp618351
PHP-bcmath: Installed
PHP-ctype: Installed
PHP-curl: Installed
PHP-intl: Installed
PHP-json: Installed
PHP-mbstring: Installed
PHP-openssl: Installed
PHP-redis: Installed
Database: mysql (8.0.26)
Bootstrap: Writable
Storage: Writable
========= END =========
```

There are no errors in the logs.

**Comment by samihsoylu** [comment]
Here is a demonstration of my issue, it is quite literally a 404 page. Even some basic instructions to debug this would be greatly appreciated

https://user-images.githubusercontent.com/7690781/142738896-db3555e8-ad5f-4547-bde3-b604dcbd0130.mp4

**Comment by ghost** [comment]
This is not something new i had informed the developer on this before.

why don’t you try installing pixelfed using yunohost? It’s the easiest way to get rid of most of the bugs 

https://yunohost.org/en/install/hardware:vps_debian

**Comment by samihsoylu** [comment]
Closed due to no response from the repository owner
