### ISSUE TITLE
Federation not working?

### ISSUE THREAD

**Issue by Kreibich04** [pixelfed/support#161]
Hi,

i recently setup my pixelfed instance, in hope I could successfully federate with other instances and platforms.
It currently doesn't seem to do so.
When looking for remote users, I see an completly empty profile, 0 followers, etc. and only after refreshing a profile picture.
When following others, they don't get the notification / the follow isn't transferred. Same the other way round, except mastodon shows me, it had to wait for the follow request to be accepted. No sign of a follow request in pixelfed, except my profile is public anyways.

When I create a post is is not distributed to my followers, as pixelfed seems to not have recognized the followers.

Settings for AP in .env are made, everything regarding federation is set to true. I also did clear / reload the config cache with artisan config:cache

Not sure if the error is on my side or on software side.

**Comment by thomasjwebb** [comment]
I'm having the same issue with my new pixelfed instance. I'm on the latest tag (v0.11.4). I do see in the dashboard that it does say for me that the instance actor isn't cached. Not sure if that's relevant or not.

**Comment by creideiki** [comment]
I'm seeing something similar on my new instance, running 0.11.4-4393780a on PHP 8.1.12.

From Pixelfed, I can't see any remote information whatsoever.

From Mastodon, I can see my Pixelfed account, and pasting the URL of a Pixelfed post into Mastodon's search bar shows that post. Attemping to follow the Pixelfed account from Mastodon results in nothing on the Pixelfed side and an "Awaiting approval" message on Mastodon, even though the Pixelfed account is not locked.

All the `AP_` settings in `.env` are turned on, and the cache has been updated:
```
ACTIVITY_PUB="true"
AP_REMOTE_FOLLOW="true"
AP_INBOX="true"
AP_OUTBOX="true"
AP_SHAREDINBOX="true"
```

 The Pixelfed admin dashboard says:
* ACTIVITYPUB instance actor created: ✅ true
* ACTIVITYPUB instance actor cached: ❌ false
