### ISSUE TITLE
I'm not able to make my account browsable without a login

### ISSUE THREAD

**Issue by steinarb** [pixelfed/support#188]
I have tried to make my account https://pixelfed.social/i/web/profile/305714547921129472 publicly accessible, but if I try opening this URL in an anonymous window I am redirected to the login window.

I have the following privacy settings:

1. Private Account (off)
2. Disable Search Engine Indexing (off)
3. Include public posts in search results (on)
4. Show on Directory (on)
5. Receive direct messages from anyone (off)  (I don't want direct messages on pixelfed, but I will turn it on if that is neccessary?)
6. Show follower count (on)
7. Show following count (on)
8. Enable Atom Feed (on)

**Comment by dansup** [comment]
Fixed!

**Comment by steinarb** [comment]
Verified fixed! Lovely! Thanks! :smiley:
