### ISSUE TITLE
Cannot find 'BeyondCode\LaravelWebSockets\WebSocketsServiceProvider' after migrating to v0.12.3

### ISSUE THREAD

**Issue by carstencodes** [pixelfed/support#202]
Hi,

I recently updated from v0.12.1 to v0.12.3.

My docker images keep restarting, as `php artisan storage:link` always exits due to missing beyondcode\laravelwebsockets classes.

They are still part of the config, as [the websockets.php config file](https://github.com/pixelfed/pixelfed/blob/v0.12.3/config/websockets.php) shows, but were removed by @dansup in a [commit](https://github.com/pixelfed/pixelfed/commit/f7bbf3eab58eeeee5d38c76c8042c28d6c64972c) to update to [laravel 11](https://github.com/pixelfed/pixelfed/pull/5196).

I am definitely no pro in PHP, and I have no idea of laravel, so I don't know how to disable this.

I reverted the container to v0.12.1 and its running like a charm.

This is the log output of the container:

```
pixelfed-worker  | [entrypoint / entrypoint.sh] - ============================================================
pixelfed-worker  | [entrypoint / entrypoint.sh] - Executing [/docker/entrypoint.d/10-storage.sh]
pixelfed-worker  | [entrypoint / entrypoint.sh] - ============================================================
pixelfed-worker  | [entrypoint / 10-storage.sh] - 👷 Running [cp --force --recursive storage.skel/. ./storage/] as [www-data]
pixelfed-worker  | [entrypoint / 10-storage.sh] - ✅ OK!
pixelfed-worker  | [entrypoint / 10-storage.sh] - 👷 Running [php artisan storage:link] as [www-data]
pixelfed-worker  | [entrypoint / 10-storage.sh] - (stdout) 
pixelfed-worker  | [entrypoint / 10-storage.sh] - (stdout) In Application.php line 933:
pixelfed-worker  | [entrypoint / 10-storage.sh] - (stdout) 
pixelfed-worker  | [entrypoint / 10-storage.sh] - (stdout) Class "BeyondCode\LaravelWebSockets\WebSocketsServiceProvider" not found
pixelfed-worker  | [entrypoint / 10-storage.sh] - (stdout) 
pixelfed-worker  | [entrypoint / 10-storage.sh] - (stdout) 
pixelfed-worker  | [entrypoint / 10-storage.sh] - ERROR - ❌ Error!
pixelfed-worker  | [entrypoint / entrypoint.sh] - 🔓 Releasing lock [/var/www/storage/docker/lock/entrypoint.sh]
pixelfed-worker exited with code 0
```

What can I do to make pixelfed 0.12.3 run?

/cc @jippi

**Comment by jippi** [comment]
remove your cache files in `docker-compose-state/data/pixelfed/cache`

**Comment by carstencodes** [comment]
> remove your cache files in `docker-compose-state/data/pixelfed/cache`

Sorry, there is no such folder.

I tried using docker builder prune and docker compose build --no-cache. But this did not help either ...

**Comment by carstencodes** [comment]
@jippi Any other idea?

**Comment by LM1LC3N7** [comment]
@carstencodes , I think @jippi was not refering to docker build cache, but to volume "bootstrap" in the docker compose.
Removing it (or changing the name of the volume) worked for me!

**Comment by carstencodes** [comment]
@LM1LC3N7 Thanks for the tip. Now it works again.

@jippi Maybe as a point of improvement: If the bootstrap cache has not been created with the current, it might be wise to clear it before
