### ISSUE TITLE
«Oops, something went wrong» after upgrade to v0.10.6

### ISSUE THREAD

**Issue by stemy2** [pixelfed/support#3]
Hello,

I can't use pixelfed anymore since the last update. After logging on, i have the message «Oops, something went wrong». I tried the solution mentioned [here](https://github.com/pixelfed/pixelfed/issues/694), but it solved nothing.

**Comment by stemy2** [comment]
Just upgraded to the last version. Solved absolutly nothing.

**Comment by Gregor2019** [comment]
Dear all, I got the same Issue - Installed all New Ubuntu 18.04.3 LTS / pixelfed -> 0.10.6 / PHP 7.3.10-1 / nginx 1.14.0. All seems to work only the timeline does cause an Error "Oops, something went wrong" / Mozilla Debugger ->"Error: Request failed with status code 500" | NETWORK view:
Request URL:https://Pixelfed.test.com/api/pixelfed/v1/timelines/home?max_id=0&limit=5
Request method:GET
Remote address:X.X.X.X:443
Status code: 500
Version:HTTP/2.0
Referrer Policy:no-referrer-when-downgrade

Did try all I found config php/mysql/.env - also study of the log files but somehow I don't find any helping hint.

Thank you for Help to get it run 100%.

**Comment by Gregor2019** [comment]
Today I did go back to the beginning - and I found a note whats needs to be considered at installation time -> https://docs.pixelfed.org/installing-pixelfed/prerequisites.html#php
_"A **note about php-redis vs. predis:**
Make sure you do NOT have the redis PHP extension installed/enabled! Pixelfed uses the predis
library internally, so the presence of any Redis extensions can cause issues."_
in my case that was the Issue - I did disable the redis PHP extension -> and now the Timeline works...

**Comment by stemy2** [comment]
This is weird. Previous pixelfed version worked fine, even with redis activated. And this is a problem if i want to use an app that needs redis. And when i loaded pixelfed with redis disabled, it didn't load at all.

**Comment by trwnh** [comment]
Predis requires env vars to be set I'm pretty sure

php-redis is unsupported and pixelfed in a shared environment is currently not supported either. this might change after laravel 6, as laravel is moving to deprecating predis

https://laravel.com/docs/5.7/redis
https://laravel.com/docs/6.x/redis

thinking of making an issue template with FAQs, just haven't gotten around to it yet!

**Comment by stemy2** [comment]
Upgrade solved it.
