### ISSUE TITLE
error 500 when getting api/v1/timelines/* or api/v2/*

### ISSUE THREAD

**Issue by salvadorpla** [pixelfed/support#44]
My instance throws 500 error when getting:

/api/v1/timelines/public?page=1
/api/v1/timelines/home?page=1

and

/api/v2/comments/*
/api/v2/profile/*
/api/v2/discover/posts

I did try a fresh install following https://github.com/pixelfed/pixelfed/blob/dev/README.md and by using also a new fresh database but same errors.

No errors when accesing:

/api/v1/notifications
/api/v1/accounts/verify_credentials

Any clue?
Thank you

**Comment by ghost** [comment]
@trwnh running PHP 7.3.10 so must be another reason.

php -v
PHP 7.3.10 (cli) (built: Sep 27 2019 11:41:00) ( NTS )

**Comment by trwnh** [comment]
Weird. Any version 7.2 or newer should be able to handle trailing commas. Could maybe a caching issue of some sort?

**Comment by ghost** [comment]
I will do some more deep research. Will come back if any findings.
By the way, this is not related to a new install, it's an update from 0.10.0.

**Comment by dansup** [comment]
@salvadorpla fixed in https://github.com/pixelfed/pixelfed/pull/2083/commits/599ab152a7b354920350388ad2fab4bbb13fa1f0, sorry about that!
