### ISSUE TITLE
[discover.places] not defined

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/support#5]
Hello,

When I try to load the url of any place, I have an error page. For example : 
https://pixelfed.fr/discover/location/country/afghanistan

In the log I have that : 
`[discover.places] not defined. in /home/pixelfed/live/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:388`

What can I do ?

**Comment by pete-harris** [comment]
Was there a resolution to this? I'm getting the same issue after upgrading to the latest 0.10.8 release (missing out a few versions in between) on Debian Linux.
