### ISSUE TITLE
ActivityPub env vars out of date on Yunohost

### ISSUE THREAD

**Issue by lapineige** [pixelfed/support#57]
Hello,

First of all, I'm sorry as this is probably a duplicate (even if I did not found any detailed answer for a similar problem in the other issues), but version after version I still can't activate federation - or maybe it's just not working -, nor remote follow and so on. Even after searching so much for some documentation about it.

**Version** : 0.10.6 (I previously had the same issue in 0.9.x versions), installed with Yunohost (https://github.com/YunoHost-Apps/pixelfed_ynh).

**The problem** : federation from my Pixelfed is not working (or not activated correctly).
I can't remote follow (using both URL or `pseudo@domain.tld` syntax), I have no federated TL.
Commenting, following my profile and seeing its content is possible from mastodon, at least.

**What I did** :
- configure `.env` file with `ACTIVITY_PUB=true`, `REMOTE_FOLLOW=true`, `ACTIVITYPUB_INBOX=true`, `ACTIVITYPUB_SHAREDINBOX=true`.
- edit `config/federation.php` and set those parameters as `true`
- do all the `php7.3 artisan cache:clear` stuff and even a `service php7.3-fpm` restart, and lots of reboot since first try.

What's going on ?
How can I activate federation ?
How can I check if it's working, buggy, or just not activated ?

Thanks a lot :)

**Comment by trwnh** [comment]
`REMOTE_FOLLOW` has become `AP_REMOTE_FOLLOW`, and `ACTIVITYPUB_INBOX` has become
`AP_INBOX`. (`ACTIVITYPUB_SHAREDINBOX` has become `AP_SHAREDINBOX` as well, but currently isn't as widely used as the other vars.)

**Comment by lapineige** [comment]
Oh ok, that's the issue ! I missed that change.
Thanks a lot, it worked 🎉

(btw, what's the use of `AP_SHAREDINBOX` ?)

**Comment by trwnh** [comment]
sharedInbox is an endpoint that lets servers send public messages to an entire server rather than to an individual actor. it's helpful in cases where multiple actors follow the same remote actor.
