### ISSUE TITLE
Image upload > 1M does'nt work

### ISSUE THREAD

**Issue by ghost** [pixelfed/support#58]
Tried to upload images large than 1M in size, but it always stops with an error message:

![MVO Pixel](https://user-images.githubusercontent.com/58190287/69642737-886e7080-1062-11ea-915d-f527b0ecdf67.png)

.env 

> MAX_PHOTO_SIZE=15000
> MAX_CAPTION_LENGTH=150
> MAX_ALBUM_LENGTH=4

**Comment by trwnh** [comment]
Did you edit your php.ini to set your max upload size? https://docs.pixelfed.org/installing-pixelfed/prerequisites.html#php

`post_max_size` and `upload_max_filesize` need to be set appropriately.

**Comment by ghost** [comment]
Yes - it is set to :

post_max_size | 200M
upload_max_filesize | 200M

Copied from php info

**Comment by ghost** [comment]
Adding

`client_max_body_size 15M;`

to nginx conf was the solution.
