### ISSUE TITLE
Own reply not clickable 

### ISSUE THREAD

**Issue by ghost** [pixelfed/support#59]
Answering to a comment with a reply isn't clickable:

![Memo posted a photo  22 likes](https://user-images.githubusercontent.com/58190287/69619846-93160f00-103c-11ea-9816-11e530d006e4.png)

but available

![MVO Pixel](https://user-images.githubusercontent.com/58190287/69619859-9a3d1d00-103c-11ea-9061-9743320d3648.png)

**Comment by dansup** [comment]
@memo-567 This is a deployment error, not a bug. If ```php artisan route:cache``` is not working, than its likely something is missing or not configured properly.

Please run ```php artisan self-diagnosis``` and report the results here.

**Comment by ghost** [comment]
Done:

> 
> |-------------------------------------
> | Common Checks
> |-------------------------------------
> Running check 1/11: App key is set...  ✔
> Running check 2/11: The correct PHP version is installed...  ✔
> Running check 3/11: The database can be accessed...  ✔
> Running check 4/11: All directories have the correct permissions...  ✔
> Running check 5/11: The environment file exists...  ✔
> Running check 6/11: The example environment variables are set...  ✔
> Running check 7/11: Required locales are installed...  ✘
> Running check 8/11: Maintenance mode is not enabled...  ✔
> Running check 9/11: The migrations are up to date...  ✔
> Running check 10/11: The required PHP extensions are installed...  ✔
> Running check 11/11: The storage directory is linked...  ✔
> 
> |-------------------------------------
> | Environment Specific Checks ()
> |-------------------------------------
> 
> The following checks failed:
> The following locales are missing:
> en_US

**Comment by ghost** [comment]
At the other hand `locale -a` result is:

> C
> C.UTF-8
> de_DE.utf8
> en_US.utf8
> POSIX

**Comment by ghost** [comment]
May be I gave a confusing answer? I'm a native German speaking admin? 😏

`php artisan route:cache` works! - but without without a desired result.

**Comment by ghost** [comment]
![201911271052](https://user-images.githubusercontent.com/58190287/69795861-38f88380-11cd-11ea-8385-bacc6a11a30d.png)

**Comment by ghost** [comment]
> How old is that instance? 

It is three days old but I pulled last updates.

**Comment by ghost** [comment]
Additional:

Hovering over "view replies" is changing the pointer from arrow to hand but now link appears in lower left corner of chrome / firefox

**Comment by dansup** [comment]
Fixed in latest commits.
