### ISSUE TITLE
Bootstrap and jquery

### ISSUE THREAD

**Issue by Monteleone** [pixelfed/support#60]
I tried to add some new bootstrap elements to a blade page, such as buttons or menu and only the buttons seems to work.
If I use:

```

<button type="button" class="btn btn-primary">Primary</button>
<button type="button" class="btn btn-outline-info d-block mx-auto my-3">Don't Miss Out, Register Now</button>
<button type="button" class="btn btn-outline-primary">Primary</button>
<button type="button" class="btn btn-outline-secondary">Secondary</button>
<button type="button" class="btn btn-outline-success">Success</button>
<button type="button" class="btn btn-outline-info">Info</button>
<button type="button" class="btn btn-outline-warning">Warning</button>
<button type="button" class="btn btn-outline-danger">Danger</button>

```
They all works. But if I use a menu or a slider:

	<input id="ex1" data-slider-id='ex1Slider' type="text" data-slider-min="0" data-slider-max="20" data-slider-step="1" data-slider-value="14"/>

it doesn't work. I think jquery or bootstrap js is not correctly loaded.
Can you give me some advice?

ty

**Comment by dansup** [comment]
@Monteleone What slider are you trying to use? Bootstrap only has the ```range``` element https://getbootstrap.com/docs/4.4/components/forms/#range
