### ISSUE TITLE
[TOR] Premature Session Invalidation

### ISSUE THREAD

**Issue by Jookia** [pixelfed/support#64]
Pixelfed is unusable for me since any kind of period of inactivity seems to trigger an auth check. I'm using Firefox and Tor on nfg.zone running 0.10.6

**Comment by dansup** [comment]
@Jookia I was wrong, the instance you were on did not change the SESSION_TIMEOUT. They have since updated the timeout to 2 days and we have updated the .env.example with a 2 day value.
