### ISSUE TITLE
Access to /i/media/preview/ urls always create a 404

### ISSUE THREAD

**Issue by mgisbers** [pixelfed/support#68]
After adding a post the preview including the filter previews don't show up.

On the server a error 404 can be found in the access_log:

> a.b.c.d - - [12/Jan/2020:17:49:53 +0100] "GET /i/media/preview/118135833604788224/27/1578847792?expires=1578851392&signature=112edc5776fbf289627d894c8d0823c816cf9916aff61e6520e2e308aa8ce83e HTTP/1.0" 404 10595

The error_log and laravel.log don't show an error. Accessing that url by curl results in an 404 error page.

Any idea where to look?

**Comment by dansup** [comment]
@mgisbers This is a configuration/deployment issue and not a bug so I have transferred it to our support tracker.

Please provide more information on your configuration/deployment setup.

**Comment by efelon** [comment]
For me, I myself was the problem when forgetting to revert nginx configuration tests. Sorry for the noise from my side.

@mgisbers please try to add the following lines to your backend server in the "location ~ \\.php$" block:

```
#fix preview problem
fastcgi_param REQUEST_SCHEME $http_x_forwarded-proto;
fastcgi_param HTTPS $proxy_https if_not_empty;
```

Also look at what @Strubbl wrote in his [comment](https://github.com/pixelfed/support/issues/68#issuecomment-573630978) above.
