### ISSUE TITLE
Post more than one pic AND set location

### ISSUE THREAD

**Issue by Strubbl** [pixelfed/support#71]
Is it somehow possible to put more than one picture in a post and set the location where the pics were made?

Currently i only see the option to post multiple pics without location info. Or i can post one pic with location set.

**Comment by efelon** [comment]
What version are you on?

On 0.10.7 (dev) you can set a location once for the set. Here I added 2 pictures and clicked "next" on the top right corner once the pictures were uploaded:

![image](https://user-images.githubusercontent.com/10722552/72796252-4bc48d00-3c3f-11ea-9bf9-e6456c593a4c.png)

**Comment by Strubbl** [comment]
Thanks for that hint. i updated and the issue is solved :)
