### ISSUE TITLE
Images & avatars don't show

### ISSUE THREAD

**Issue by ghost** [pixelfed/support#76]
It's a fresh install of the latest development build running with Apache.

I think the cause of the problem is that Pixelfed can't open files inside /storage/ and just throws the "Sorry, this page isn't available" message at me.

It should be done via htaccess to redirect /public/storage to /storage/app/public

It doesn't work with the default htaccess nor the alternative htaccess on the docs page.

**Comment by ghost** [comment]
Thanks for the reply. It is not a permission issue, all folders & files are owned by the same user.

**Comment by UnleavenedEagle** [comment]
Solved, symlink was not properly made.

**Comment by ghost** [comment]
I have solved the problem, it was not to do with the Pixelfed software but the Apache configuration.
