### ISSUE TITLE
No avatars to/from other networks

### ISSUE THREAD

**Issue by pludi** [pixelfed/support#97]
Currently my setup doesn't show the avatars for any profiles interacting with my posts, verified for Pleroma and Mastodon.

Possibly related, I can't see my avatar when viewing the profile from Mastodon.

Within the instance avatars work fine, can be changed & are displayed correctly.

Can't see obvious errors in the Lavarel or Horizon logs.

Pixelfed 0.10.9 on Debian 10.4, PHP 7.3.14, nginx 1.14.2

Any help appreciated.

**Comment by Strubbl** [comment]
Maybe the issue https://github.com/pixelfed/pixelfed/issues/1629 is related?
